### ISSUE TITLE
nifi download task timeouts 

### ISSUE THREAD

**Issue by srajasimman** [Sunbird-cQube/cQube_Edu#587]
nifi download task timeouts and every time it's downloading the file even it already exists. (the file size is almost 1.5G 😀 )

https://github.com/Sunbird-cQube/cQube_Edu/blob/005d5b35624fe32e112b96e9b89d64c96149a6c1/devops/ansible/roles/nifi_install/tasks/install_nifi.yml#L13-L18

mentioning the destination file name to avoid downloading the file if it exists.

```yml
- name: Download NiFi
  get_url:
    url: https://archive.apache.org/dist/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.tar.gz
    dest: ~/nifi/nifi-{{ nifi_version }}-bin.tar.gz
    mode: "0644"
  tags: install

```
@asifbasha61
